name = "StarterName"
author = "MrKoookaburra"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0861a41aeb3a2056ddf59e845c54c9157c59226c6f635d31722053e9143b8b39"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
