name = "StarterName"
author = "MrKoookaburra"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfc30699694b2d6dd88b195debd612942f786f76a13932c79ccb3a4d82bae958"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
