name = "StarterName"
author = "MrKoookaburra"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45ec5d254436463bfb1bb968a8d8fe5c357dd81a82eba7a36625dfaaa3662fb4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
