# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				axolotl = true
				arrow = true
				trader_llama = true
				cow = true
				tropical_fish = true
				pig = true
				slime = true
				pillager = true
				allay = true
				iron_golem = true
				skeleton = true
				bat = true
				area_effect_cloud = true
				cat = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				player = true
				dolphin = true
				pufferfish = true
				item = true
				turtle = true
				villager = true
				salmon = true
				zombie_villager = true
				ocelot = true
				vindicator = true
				horse = true
				leash_knot = true
				cod = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.tconstruct]
				sky_slime = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.cobblemon]
				pokemon = true

